-- GENERATED by scripts/fortis/baseline/build.mjs from supabase/migrations/20260429013958_0008_tenant_onboarding_state.sql. Do not edit.
-- =============================================================================
-- Migration 008_tenant_onboarding_state (applied via Supabase MCP)
-- =============================================================================
-- Source of truth: docs/specs/02-spec-*.md
-- Stub kept here to make supabase/migrations/ reflect remote
-- supabase_migrations.schema_migrations. See MANIFEST.md for the row index.
SELECT 1;
