-- GENERATED by scripts/fortis/baseline/build.mjs from supabase/migrations/20260428200331_0007_security_hardening.sql. Do not edit.
-- =============================================================================
-- Migration 007_security_hardening (applied via Supabase MCP)
-- =============================================================================
-- Source of truth: docs/specs/01-spec-*.md
-- Stub kept here to make supabase/migrations/ reflect remote
-- supabase_migrations.schema_migrations. See MANIFEST.md for the row index.
SELECT 1;
