-- GENERATED by scripts/fortis/baseline/build.mjs from supabase/migrations/20260429021857_0009_expand_messaging_constraints.sql. Do not edit.
-- =============================================================================
-- Migration 009_expand_messaging_constraints (applied via Supabase MCP)
-- =============================================================================
-- Source of truth: docs/specs/03-spec-*.md
-- Stub kept here to make supabase/migrations/ reflect remote
-- supabase_migrations.schema_migrations. See MANIFEST.md for the row index.
SELECT 1;
