-- GENERATED by scripts/fortis/baseline/build.mjs from supabase/migrations/20260721120001_0055_whatsapp_media_bucket.sql. Do not edit.
-- 0055: bucket privado whatsapp-media — binários de mídia do WhatsApp
-- (Onda 0 do épico inbox-multimodal). O acesso é exclusivamente via service
-- role (upload pelo worker, signed URL pelo endpoint) — sem policies de
-- object_storage.objects para anon/authenticated.
insert into object_storage.buckets (id, name, public, file_size_limit)
values ('whatsapp-media', 'whatsapp-media', false, 52428800)
on conflict (id) do update set file_size_limit = excluded.file_size_limit;
