-- GENERATED by scripts/fortis/baseline/build.mjs from supabase/migrations/20260428200128_0005_ai_rag.sql. Do not edit.
-- =============================================================================
-- Migration 005_ai_rag (applied via Supabase MCP)
-- =============================================================================
-- Source of truth: docs/specs/05-spec-*.md
-- Stub kept here to make supabase/migrations/ reflect remote
-- supabase_migrations.schema_migrations. See MANIFEST.md for the row index.
SELECT 1;
