-- GENERATED by scripts/fortis/baseline/build.mjs from supabase/migrations/20260428195513_0002_event_log_and_compat.sql. Do not edit.
-- =============================================================================
-- Migration 002_event_log_and_compat (applied via Supabase MCP)
-- =============================================================================
-- Source of truth: docs/specs/02-spec-*.md
-- Stub kept here to make supabase/migrations/ reflect remote
-- supabase_migrations.schema_migrations. See MANIFEST.md for the row index.
SELECT 1;
