#!/usr/bin/env node
// Builds database/baseline/baseline.sql from the upstream supabase/baseline.sql.
//   node scripts/fortis/baseline/build.mjs          # write
//   node scripts/fortis/baseline/build.mjs --check  # fail if stale or unsafe (CI)
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { neutralize } from './neutralize.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const source = 'supabase/baseline.sql';
const target = 'database/baseline/baseline.sql';
const HEADER = `-- GENERATED by scripts/fortis/baseline/build.mjs from ${source}. Do not edit.
-- Apply as crm_owner on a database prepared by database/platform/0001_fortis_platform.sql,
-- then database/platform/0100_fortis_tenancy.sql. See docs/fortis/adr/0002-tenancy-and-rls.md.
`;

const { sql, counts, residuals } = neutralize(readFileSync(join(root, source), 'utf8'));
if (residuals.length) {
  console.error(`Supabase platform references left after the rewrite (${residuals.length}):`);
  for (const r of residuals.slice(0, 20)) console.error(`  ${r}`);
  console.error('Add a mapping in scripts/fortis/baseline/neutralize.mjs; never ship them.');
  process.exit(1);
}
const output = HEADER + sql;
if (process.argv.includes('--check')) {
  let current = null;
  try {
    current = readFileSync(join(root, target), 'utf8');
  } catch {}
  if (current !== output) {
    console.error(`${target} is stale: run node scripts/fortis/baseline/build.mjs`);
    process.exit(1);
  }
  console.info(`${target} is current`);
} else {
  writeFileSync(join(root, target), output);
  const total = Object.values(counts).reduce((a, b) => a + b, 0);
  console.info(`wrote ${target} (${total} rewrites)`);
}
