#!/usr/bin/env node
// Builds the platform-neutral schema from the upstream Supabase sources:
//   supabase/baseline.sql      → database/baseline/baseline.sql
//   supabase/migrations/*.sql  → database/upstream-migrations/*.sql
//     (the history, for update paths and tests that apply one migration)
//
//   node scripts/fortis/baseline/build.mjs          # write
//   node scripts/fortis/baseline/build.mjs --check  # fail if stale or unsafe (CI)
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { neutralize } from './neutralize.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const MIGRATIONS_SOURCE = 'supabase/migrations';
const MIGRATIONS_TARGET = 'database/upstream-migrations';
const header = (source) => `-- GENERATED by scripts/fortis/baseline/build.mjs from ${source}. Do not edit.
`;
const BASELINE_HEADER = `${header('supabase/baseline.sql')}-- Apply as crm_owner on a database prepared by database/platform/0001_fortis_platform.sql,
-- then database/platform/0100_fortis_tenancy.sql. See docs/fortis/adr/0002-tenancy-and-rls.md.
`;

function outputs() {
  const out = new Map();
  const problems = [];
  const add = (source, target, prefix) => {
    const { sql, residuals } = neutralize(readFileSync(join(root, source), 'utf8'));
    residuals.forEach((r) => problems.push(`${source}:${r}`));
    out.set(target, prefix + sql);
  };
  add('supabase/baseline.sql', 'database/baseline/baseline.sql', BASELINE_HEADER);
  for (const f of readdirSync(join(root, MIGRATIONS_SOURCE)).filter((f) => f.endsWith('.sql')).sort()) {
    add(`${MIGRATIONS_SOURCE}/${f}`, `${MIGRATIONS_TARGET}/${f}`, header(`${MIGRATIONS_SOURCE}/${f}`));
  }
  return { out, problems };
}

// The tenancy overlay re-states upstream's latest fn_user_org_ids() body.
// Pin its hash so an upstream change fails here instead of being overridden.
const OVERLAY = 'database/platform/0100_fortis_tenancy.sql';
const LAST_BODY = /create or replace function public\.fn_user_org_ids\(\)\s*returns setof uuid[^$]*\$f\$([\s\S]*?)\$f\$;/gi;

function upstreamBodyHash(baselineSql) {
  const bodies = [...baselineSql.matchAll(LAST_BODY)];
  if (!bodies.length) return null;
  return createHash('sha256').update(bodies.at(-1)[1].trim()).digest('hex');
}

const { out, problems } = outputs();
const bodyHash = upstreamBodyHash(out.get('database/baseline/baseline.sql'));
const pinned = /upstream-body-sha256: ([0-9a-f]{64})/.exec(readFileSync(join(root, OVERLAY), 'utf8'))?.[1];
if (!bodyHash || bodyHash !== pinned) {
  problems.push(
    `${OVERLAY}: upstream fn_user_org_ids() changed (sha256 ${bodyHash ?? 'not found'}, pinned ${pinned ?? 'none'}); ` +
      'port the new body into the overlay, then update the pinned hash',
  );
}
if (problems.length) {
  console.error(`Supabase platform references left after the rewrite (${problems.length}):`);
  problems.slice(0, 20).forEach((p) => console.error(`  ${p}`));
  console.error('Map new platform objects in scripts/fortis/baseline/neutralize.mjs (never ship them); port upstream changes into the overlay.');
  process.exit(1);
}

const targetDir = join(root, MIGRATIONS_TARGET);
const existing = existsSync(targetDir)
  ? readdirSync(targetDir).map((f) => `${MIGRATIONS_TARGET}/${f}`)
  : [];
const orphans = existing.filter((p) => !out.has(p));

if (process.argv.includes('--check')) {
  const stale = [...out].filter(([p, content]) => {
    try {
      return readFileSync(join(root, p), 'utf8') !== content;
    } catch {
      return true;
    }
  });
  if (stale.length || orphans.length) {
    console.error(`database/ is stale (${stale.length} changed, ${orphans.length} orphan): run node scripts/fortis/baseline/build.mjs`);
    process.exit(1);
  }
  console.info(`database/ is current (${out.size} files)`);
} else {
  mkdirSync(targetDir, { recursive: true });
  mkdirSync(join(root, 'database/baseline'), { recursive: true });
  for (const [p, content] of out) writeFileSync(join(root, p), content);
  orphans.forEach((p) => rmSync(join(root, p)));
  console.info(`wrote ${out.size} files, removed ${orphans.length} orphan(s)`);
}
